// Angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'prototipado-angular';
}

<div>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <a href="#" class="navbar-brand">OTSEDF</a>
    <div class="navbar-nav mr-auto">
      <li class="nav-item">
        <a routerLink="tutorials" class="nav-link">Tutorials</a>
      </li>
      <li class="nav-item">
        <a routerLink="add" class="nav-link">Add</a>
      </li>
    </div>
  </nav>

  <div class="container mt-3">
    <router-outlet></router-outlet>
  </div>
</div>

// Producto Integrador/src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
 <div>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <RouterLink to="/" class="navbar-brand">OTSEDF</RouterLink>
      <div class="navbar-nav mr-auto">
        <li class="nav-item">
          <RouterLink to="/tutorials" class="nav-link">Tutorials</RouterLink>
        </li>
        <li class="nav-item">
          <RouterLink to="/add" class="nav-link">Add</RouterLink>
        </li>
      </div>
    </nav>

    <div class="container mt-3">
      <RouterView />
    </div>
  </div>

</template>
